### ISSUE TITLE
Consulta Codigo con Observador

### ISSUE THREAD

**Issue by IvoGC** [IvoGC/Actividad3_SCII#4]
Hola profe el codigo del observador hay algo que estoy implementando mal y no me doy cuenta bien donde es, supongo que es que le cambio de un vector fila a un vector columna en algun momento de la iteracion en tiempo continuo pero no puedo resolverlo, porque cuando cambio una cosa me da error en otro lado.
https://github.com/IvoGC/Actividad3_SCII/blob/main/motor_discreto_con_integrador_observador.m#L90
Basicamente me da error en la generacion de la entrada o en la asignacion de los Xhat punto

**Comment by Julianpucheta** [comment]
Está incorrecta la B del Dual.

**Comment by IvoGC** [comment]
Pero profe si lo pongo asi completo, me tira error cuando busco el controlador Ko y me dice que debe ser simetrico, yo defini la C con dos vectores porque quiero que mi salida tenga tantoo el angulo tita como la velocidad angular Wr para poder contrastarlas con la salida del observador y obtener la señal e(t) nose si eso es correcto

**Comment by Julianpucheta** [comment]
La C con dos filas del sistema es la B del dual para calcular el Obs. Luego el Obs tiene dos columnas y podrás multiplcarla por el error de Y que tiene dos componentes. Ahora está incorrecto el Obs así implementado.

**Comment by IvoGC** [comment]
Entonces profe como esta ahora deberia estar correcto?
https://github.com/IvoGC/Actividad3_SCII/blob/main/motor_discreto_con_integrador_observador.m#L41

**Comment by Julianpucheta** [comment]
Si. B del dual tiene que tener dos columnas.
